
var products = [
    {"name":"Checkerboard Chair",       "model":"CMR-2024-BLK-001",  "filename":["prod.png"],      "price":"$349.99",  "description":" Introducing our stylish chair with a checkered fabric cover, the perfect addition to any modern or traditional interior. Crafted with utmost attention to detail, this chair combines comfort and elegance effortlessly. The checkered fabric cover adds a touch of sophistication, while the sturdy construction ensures durability and longevity. Whether used as a statement piece or as part of a set, this chair is sure to enhance the aesthetic appeal of any space. Experience comfort and style like never before with our exquisite checkered fabric chair. "},
    {"name":"Brass Marble table lamp",  "model":"TL-2024-SIL-002",  "filename":["prod2.png"],      "price":"$129.99",  "description":"This elegant table lamp combines the timeless beauty of marble with the sophistication of brass. Crafted with meticulous attention to detail, the lamp exudes a sense of luxury and refinement. The smooth marble base provides a sturdy foundation, while the brass accents add a touch of glamour. With its sleek design and warm glow, this lamp is the perfect addition to any modern or traditional interior. Illuminate your space with style and grace with this exquisite marble and brass table lamp. "},
    {"name":"Wall Twin Light",          "model":"WTL-2024-BRN-003", "filename":["prod3.png"],      "price":"$199.99",          "description":"Introducing our elegant wall light featuring two sleek white shades, perfect for illuminating any space with a touch of sophistication. Crafted with attention to detail, this modern fixture effortlessly combines functionality and style. The white shades provide a soft and inviting glow, creating a warm ambiance in any room. Whether used as a focal point or to enhance existing decor, this wall light is a versatile addition to any home or office setting. "},
    {"name":"Harmony Chair",            "model":"CHR-2024-GRY-004", "filename":["prod4_part1.jpg"]  ,"price":"$600",  "description":"Introducing our elegant beige chair with a sleek black base and a plush white cushion. This stylish piece combines comfort and sophistication, making it the perfect addition to any modern or contemporary space. Crafted with attention to detail, the chair's neutral color palette effortlessly complements a variety of interior styles. Whether you're looking to create a cozy reading nook or enhance your living room decor, this chair is sure to elevate your space with its timeless design and inviting appeal."},
    {"name":"Contemporary Oakwood Eight-Drawer Dresser", "model":"EDD-2024-WHT-005", "filename":["prod5_part1.png"],     "price":"$650 ",  "description":"Introducing our modern wooden dresser with eight spacious drawers, the perfect addition to any contemporary living space. Crafted with high-quality wood, this dresser combines functionality and style, providing ample storage for all your essentials. Its sleek design and clean lines add a touch of elegance to any room, while the natural wood finish adds warmth and sophistication. With its six drawers, you'll have plenty of space to organize your clothes, accessories, or any other belongings. Upgrade your home decor with this versatile and timeless piece of furniture. "},
    {"name":"Verdant Circle Table",  "model":"CT-2024-BLK-006", "filename":["prod6_part1.jpg"],     "price":"$149.50",  "description":"Introducing our stylish green table with a sleek circular base, the perfect addition to any modern interior. Crafted with precision and attention to detail, this table combines functionality with a touch of elegance. Its vibrant green color adds a pop of freshness to any space, while the circular base ensures stability and balance. Whether used as a dining table, workspace, or decorative piece, this versatile table is sure to enhance the aesthetic appeal of your home or office. "},
    {"name":"BrownGlow Table Lamp",  "model":"TL-2024-GLD-007", "filename":["prod7_part1.jpg"],     "price":"$399.99",  "description":"Introducing our elegant table lamp with a sleek brown shade and matching cord. This sophisticated lamp effortlessly combines style and functionality, making it the perfect addition to any room. The warm brown shade creates a cozy ambiance, while the brown cord ensures a seamless and coordinated look. Illuminate your space with this timeless piece that will enhance your decor and provide a soft, inviting glow. "},
    {"name":"CloudScape Sofa",  "model":"SF-2024-BLU-008", "filename":["prod8_part1.jpg"],     "price":"$2000",  "description":"Introducing our elegant white sectional sofa, the perfect addition to any modern living space. Crafted with utmost attention to detail, this sofa exudes sophistication and comfort. The plush cushions and pillows provide exceptional support, ensuring a cozy seating experience. Its sleek design and neutral color effortlessly blend with any decor style, making it a versatile choice for your home. Whether you're entertaining guests or simply relaxing, our white sectional sofa offers both style and functionality. "},
    {"name":"CozyWood Chair Set", "model":"SRO-2894-BPK-201",  "filename":["prod9.png"],   "price":"$250",  "description":"Introducing our elegant white chair and ottoman set with sturdy wooden legs. This stylish furniture piece combines comfort and sophistication, making it a perfect addition to any modern or traditional interior. The pristine white upholstery complements the natural warmth of the wooden legs, creating a timeless and versatile design that effortlessly blends into any decor. Whether you're looking for a cozy reading nook or a chic accent piece, this chair and ottoman set is sure to elevate your space with its clean lines and impeccable craftsmanship."},
];
